name: Actions 😎

on: [push, pull_request]

jobs:
  test:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: GGK/Library
          key: GGK/Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            GGK/Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: GGK
          githubToken: ${{ secrets.GITHUB_TOKEN }}


  buildWindows:
    name: Build windows project
    runs-on: ubuntu-latest
    needs: test
    steps:

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          allowDirtyBuild: true
          projectPath: GGK/
          targetPlatform: StandaloneWindows

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build


  buildWeb:
    name: Build and deploy web project
    runs-on: ubuntu-latest
    needs: test
    steps:

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          allowDirtyBuild: true
          projectPath: GGK/
          targetPlatform: WebGL

      # Deploy
      - name: Deploy web game
        uses: JamesIves/github-pages-deploy-action@v4.7.0
        with: 
          branch: gh-pages
          folder: build/WebGL